[functions]
  directory = "netlify/functions"
  included_files = ["data/**"]

[functions."send-reminders"]
  schedule = "0 9 * * *"

[functions."scheduled-welcome-email"]
  schedule = "0 * * * *"

[functions."scheduled-weekly-broadcast"]
  schedule = "0 14 * * *"

  [[functions]]
  name = "scheduled-reengagement"
  schedule = "0 9 * * *"

[[headers]]
  for = "/website/admin-panel.html"
  [headers.values]
    Basic-Auth = "markeb:Markebmedia230301"

[[headers]]
  for = "/internal/markeb-sales-system"
  [headers.values]
    Basic-Auth = "markeb:Markebmedia230301"

[[headers]]
  for = "/internal/commercial-intelligence-framework.html"
  [headers.values]
    Basic-Auth = "markeb:Markebmedia230301"

[[headers]]
  for = "/website/client-map.html"
  [headers.values]
    Basic-Auth = "markeb:Markebmedia230301"

[[headers]]
  for = "/website/data-insights.html"
  [headers.values]
    Basic-Auth = "markeb:Markebmedia230301"

[[headers]]
  for = "/internal/interview.html"
  [headers.values]
    Basic-Auth = "markeb:Markebmedia230301"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200